
server:
    port: 8080
#    servlet:
#        context-path: /api
    tomcat:
        basedir: /tomcatCache

#一般我们会做3个配置,其余默认即可
license:
    subject: pushi-kn-graph
    publicAlias: SYSHLANG
    storePass: 12345678A
    licensePath: /Users/sixj/Desktop/license/license.lic
    publicKeysStorePath: /Users/sixj/Desktop/license/publicCerts.keystore

